apiVersion: apps/v1
kind: Deployment 
metadata:
  name: postgres-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PGPASSWORD
                  name: pgpassword
          volumeMounts:
            - mountPath: /var/lib/postgresql/data #gdje u kontejneru zelimo volumen
              name: postgres-storage #treba odgovarati name u volumes
              subPath: postgres #sve spremljenu u kontejneru s ovim se sprema i u postgres mapu u volumenu koji je prisutan lokalno
      volumes:
        - name: postgres-storage 
          persistentVolumeClaim:
            claimName: database-pvc